on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build docs
        run: cargo doc 
      - name: Copy docs and push to gh-pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout gh-pages || git checkout --orphan gh-pages

          rm -rf docs
          cp -r target/doc ./docs
          echo '<meta http-equiv = "refresh" content = "0; url = libexif/index.html" />' >> docs/index.html
          git add docs
          git commit -am "Generated docs"
          git push -u origin gh-pages
